/** Municipios y ciudades de salida habituales en República Dominicana. */
export const CIUDADES_RD = [
  "Altamira",
  "Arenoso",
  "Azua",
  "Bajos de Haina",
  "Baní",
  "Bánica",
  "Barahona",
  "Bayaguana",
  "Boca Chica",
  "Bohechío",
  "Bonao",
  "Cabarete",
  "Cabral",
  "Cabrera",
  "Cambita Garabitos",
  "Castañuelas",
  "Castillo",
  "Cayetano Germosén",
  "Cevicos",
  "Comendador",
  "Consuelo",
  "Constanza",
  "Cotuí",
  "Cristóbal",
  "Dajabón",
  "Duvergé",
  "El Cercado",
  "El Factor",
  "El Llano",
  "El Peñón",
  "El Pino",
  "El Seibo",
  "El Valle",
  "Enriquillo",
  "Esperanza",
  "Estebanía",
  "Eugenio María de Hostos",
  "Fantino",
  "Fundación",
  "Galván",
  "Gaspar Hernández",
  "Guayabal",
  "Guayacanes",
  "Guaymate",
  "Guayubín",
  "Guerra",
  "Hato Mayor",
  "Higüey",
  "Hondo Valle",
  "Imbert",
  "Jamao al Norte",
  "Jánico",
  "Jaquimeyes",
  "Jarabacoa",
  "Jima Abajo",
  "Jimaní",
  "Juan de Herrera",
  "Juan Santiago",
  "La Ciénaga",
  "La Descubierta",
  "La Mata",
  "La Romana",
  "La Vega",
  "Laguna Salada",
  "Las Charcas",
  "Las Guáranas",
  "Las Matas de Farfán",
  "Las Matas de Santa Cruz",
  "Las Salinas",
  "Las Terrenas",
  "Las Yayas de Viajama",
  "Licey al Medio",
  "Loma de Cabrera",
  "Los Alcarrizos",
  "Los Cacaos",
  "Los Hidalgos",
  "Los Ríos",
  "Luperón",
  "Maimón",
  "Mao",
  "Matanzas",
  "Mella",
  "Miches",
  "Moca",
  "Monción",
  "Monte Plata",
  "Montecristi",
  "Nagua",
  "Navarrete",
  "Neiba",
  "Nizao",
  "Oviedo",
  "Padre Las Casas",
  "Paraíso",
  "Partido",
  "Pedernales",
  "Pedro Brand",
  "Pedro Santana",
  "Pepillo Salcedo",
  "Peralta",
  "Peralvillo",
  "Piedra Blanca",
  "Pimentel",
  "Polo",
  "Postrer Río",
  "Pueblo Viejo",
  "Puerto Plata",
  "Puñal",
  "Quisqueya",
  "Ramón Santana",
  "Rancho Arriba",
  "Restauración",
  "Río San Juan",
  "Sabana de la Mar",
  "Sabana Grande de Boyá",
  "Sabana Grande de Palenque",
  "Sabana Iglesia",
  "Sabana Larga",
  "Sabana Yegua",
  "Salcedo",
  "Samaná",
  "San Antonio de Guerra",
  "San Cristóbal",
  "San Francisco de Macorís",
  "San Gregorio de Nigua",
  "San Ignacio de Sabaneta",
  "San José de las Matas",
  "San José de Ocoa",
  "San Juan",
  "San Luis",
  "San Pedro de Macorís",
  "San Rafael del Yuma",
  "Sánchez",
  "Santiago",
  "Santiago Rodríguez",
  "Santo Domingo",
  "Santo Domingo Este",
  "Santo Domingo Norte",
  "Santo Domingo Oeste",
  "Sosúa",
  "Tábara Arriba",
  "Tamayo",
  "Tamboril",
  "Tenares",
  "Vallejuelo",
  "Vicente Noble",
  "Villa Altagracia",
  "Villa González",
  "Villa Hermosa",
  "Villa Isabela",
  "Villa Jaragua",
  "Villa Los Almácigos",
  "Villa Montellano",
  "Villa Riva",
  "Villa Tapia",
  "Villa Vásquez",
  "Yaguate",
  "Yamasá",
].sort((a, b) => a.localeCompare(b, "es"));
